Newline after parenthesis if two arguments or more
Dintero/eslint-config-dintero pull request #1
Opened 2021-02-16 11:36 UTC by andersem

Will format this:

```ts
const extractAccountIdFromPayload = async (paymentProvider: SettlementProvider, allObjects: ParsedAttachment[]): Promise<string | undefined> => {
    return `hithere ${paymentProvider} ${allObjects}`;
};
```

to this:

```ts
const extractAccountIdFromPayload = async (
    paymentProvider: SettlementProvider, allObjects: ParsedAttachment[]
): Promise<string | undefined> => {
    return `hithere ${paymentProvider} ${allObjects}`;
};
```

and this:

```ts
const normalMap = async (email: ParsedMail,
    paymentProvider: SettlementProvider,
    emailDate: Date,
    originKey: string,
): Promise<SettlementFiles[]> => {
    return [];
};
```

to this:

```ts
const normalMap = async (
    email: ParsedMail,
    paymentProvider: SettlementProvider,
    emailDate: Date,
    originKey: string,
): Promise<SettlementFiles[]> => {
    return [];
};
```

https://eslint.org/docs/rules/function-paren-newline

2021-02-16 11:44 UTC, frodeaa commented
I would preferred if we used `minItems=1` as it would for `extractAccountIdFromPayload` introduce less changes if a new parameter is added to the function

2021-02-16 11:44 UTC, frodeaa approved these changes

2021-02-16 11:48 UTC, magnusjt commented
I would prefer personal judgement per case on this one. Forcing it to newline makes one line into 3+ lines. I prefer fewer lines when possible, especially when they convey just one concept. As always, just my opinion.

2021-02-16 12:43 UTC, andersem commented
I think maybe: `multiline-arguments` is better, that way you decide if you want to split into multiple lines, but when it is split, it will break between each argument.

2021-02-16 19:28 UTC, sondresj commented
> 
> 
> I think maybe `multiline-arguments` is better, that way you decide if you want to split into multiple lines, but when it is split, it will break between each argument.

Agreed, this is the best option IMO

2021-02-16 19:34 UTC, sondresj requested changes
If ya'll agree with this

2021-02-16 19:34 UTC, sondresj commented on default.js
> +        "function-paren-newline": ["error", { "minItems": 2 }],
```suggestion
        "function-paren-newline": ["error", "multiline-arguments"],
```

2021-02-17 07:14 UTC, sondresj approved these changes

2021-02-17 08:12 UTC, merged