Allow unused function args
Dintero/eslint-config-dintero pull request #3
Opened 2021-02-19 07:33 UTC by magnusjt

https://eslint.org/docs/rules/no-unused-vars#args

Adding

"no-unused-vars": ["warn", { "args": "none" }]
 "@typescript-eslint/no-unused-vars": ["warn", { "args": "none" }],

Allows unused function arguments. I've found this to be legitimate in many cases:

- Express error middleware requires that you set all arguments (basically due to bad design)
- Passing a callback to a library / other places, and documenting which arguments are available

2021-02-19 08:10 UTC, frodeaa approved these changes

2021-02-19 08:13 UTC, magnusoplenskedal approved these changes

2021-02-22 07:17 UTC, sondresj approved these changes

2021-02-24 07:06 UTC, andersem approved these changes

2021-02-24 07:45 UTC, sondresj commented
this is also an issue when spreading out properties to omit from rest, eg:
`const { secret, discard, ...rest } = foo // want to omit 'secret' and 'discard' from 'foo', and return 'rest'`

2021-02-24 07:50 UTC, sondresj requested changes

2021-02-24 07:50 UTC, sondresj commented on default.js
> +        "no-unused-vars": ["warn", { "args": "none" }],
```suggestion
        "no-unused-vars": ["warn", { "args": "none",  "ignoreRestSiblings": true }],
```

2021-02-24 07:50 UTC, sondresj commented on typescript.js
> +        "@typescript-eslint/no-unused-vars": ["warn", { "args": "none" }],
```suggestion
        "@typescript-eslint/no-unused-vars": ["warn", { "args": "none",  "ignoreRestSiblings": true }],
```

2021-02-24 08:59 UTC, svnv approved these changes

2021-02-24 09:12 UTC, merged